# Generated by Django 4.0.1 on 2022-03-01 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('courseid', models.IntegerField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=30)),
                ('coursefee', models.IntegerField(default=10000)),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('staffid', models.IntegerField(primary_key=True, serialize=False)),
                ('staffname', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('stuid', models.IntegerField(primary_key=True, serialize=False)),
                ('stuname', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studapp.course')),
            ],
        ),
    ]
